import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const dmSanas = DM_Sans ({
  subsets:["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Application root layout that applies global font and layout styles and provides application context to its children.
 *
 * @param children - The React nodes to render inside the root layout.
 * @returns The root HTML structure with the provided `children` wrapped by application providers and the global UI toaster.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSanas.className} antialiased`}
      >
        <NuqsAdapter>
        <TRPCReactProvider>
          {children}
          <Toaster/>
        </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}