import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import RootLayout from './layout'

// Mock Next.js font
vi.mock('next/font/google', () => ({
  DM_Sans: () => ({
    className: 'dm-sans-font',
  }),
}))

// Mock NuqsAdapter
vi.mock('nuqs/adapters/next/app', () => ({
  NuqsAdapter: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="nuqs-adapter">{children}</div>
  ),
}))

// Mock TRPC Provider
vi.mock('@/trpc/client', () => ({
  TRPCReactProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="trpc-provider">{children}</div>
  ),
}))

// Mock Toaster
vi.mock('@/components/ui/sonner', () => ({
  Toaster: () => <div data-testid="toaster" />,
}))

describe('RootLayout Component', () => {
  const mockChildren = <div data-testid="test-child">Test Content</div>

  it('should render children within layout', () => {
    render(<RootLayout>{mockChildren}</RootLayout>)
    expect(screen.getByTestId('test-child')).toBeInTheDocument()
  })

  it('should apply correct HTML structure', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>)
    const html = container.querySelector('html')
    expect(html).toHaveAttribute('lang', 'en')
  })

  it('should apply DM Sans font className to body', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>)
    const body = container.querySelector('body')
    expect(body).toHaveClass('dm-sans-font')
    expect(body).toHaveClass('antialiased')
  })

  it('should wrap children with NuqsAdapter', () => {
    render(<RootLayout>{mockChildren}</RootLayout>)
    expect(screen.getByTestId('nuqs-adapter')).toBeInTheDocument()
  })

  it('should wrap children with TRPCReactProvider', () => {
    render(<RootLayout>{mockChildren}</RootLayout>)
    expect(screen.getByTestId('trpc-provider')).toBeInTheDocument()
  })

  it('should render Toaster component', () => {
    render(<RootLayout>{mockChildren}</RootLayout>)
    expect(screen.getByTestId('toaster')).toBeInTheDocument()
  })

  it('should not include Google Analytics', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>)
    const scriptTags = container.querySelectorAll('script')
    
    // Check that no Google Analytics scripts are present
    scriptTags.forEach(script => {
      expect(script.src).not.toContain('googletagmanager')
      expect(script.src).not.toContain('analytics')
    })
  })

  it('should have correct metadata structure', () => {
    // Note: metadata is exported separately, not rendered in component
    // This test verifies the metadata export exists
    const { metadata } = require('./layout')
    expect(metadata).toBeDefined()
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })

  it('should render multiple children correctly', () => {
    const multipleChildren = (
      <>
        <div data-testid="child-1">Child 1</div>
        <div data-testid="child-2">Child 2</div>
      </>
    )
    
    render(<RootLayout>{multipleChildren}</RootLayout>)
    expect(screen.getByTestId('child-1')).toBeInTheDocument()
    expect(screen.getByTestId('child-2')).toBeInTheDocument()
  })

  it('should maintain proper nesting order of providers', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>)
    
    // NuqsAdapter should wrap TRPCReactProvider
    const nuqsAdapter = screen.getByTestId('nuqs-adapter')
    const trpcProvider = screen.getByTestId('trpc-provider')
    
    expect(nuqsAdapter).toContainElement(trpcProvider)
  })
})