import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const dmSanas = DM_Sans ({
  subsets:["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the application that wraps page content with global providers and UI chrome.
 *
 * Renders the top-level HTML structure with language set to English, applies the DM Sans font and antialiasing,
 * and nests the application content inside NuqsAdapter and TRPCReactProvider. Also renders a global Toaster.
 *
 * @param children - The application page content to render within the layout
 * @returns The root JSX element containing the HTML and body wrapper for the app
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSanas.className} antialiased`}
      >
        <NuqsAdapter>
        <TRPCReactProvider>
          {children}
          <Toaster/>
        </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}