import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const dmSanas = DM_Sans ({
  subsets:["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Provides the root HTML layout for the application and wraps page content with global providers and UI utilities.
 *
 * @param children - The page content to be rendered inside the layout
 * @returns The root layout element containing the HTML/body structure and provider-wrapped `children`
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSanas.className} antialiased`}
      >
        <NuqsAdapter>
        <TRPCReactProvider>
          {children}
          <Toaster/>
        </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}