import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@/test/test-utils'
import RootLayout, { metadata } from '../layout'

// Mock the font
vi.mock('next/font/google', () => ({
  DM_Sans: () => ({
    className: 'dm-sans-font',
  }),
}))

// Mock NuqsAdapter
vi.mock('nuqs/adapters/next/app', () => ({
  NuqsAdapter: ({ children }: { children: React.ReactNode }) => <div data-testid="nuqs-adapter">{children}</div>,
}))

// Mock TRPCReactProvider
vi.mock('@/trpc/client', () => ({
  TRPCReactProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="trpc-provider">{children}</div>
  ),
  useTRPC: vi.fn(),
}))

// Mock Toaster
vi.mock('@/components/ui/sonner', () => ({
  Toaster: () => <div data-testid="toaster" />,
}))

describe('RootLayout', () => {
  describe('Layout Structure', () => {
    it('should render html element with correct lang attribute', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      const htmlElement = container.querySelector('html')
      expect(htmlElement).toHaveAttribute('lang', 'en')
    })

    it('should apply DM Sans font className to body', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      const bodyElement = container.querySelector('body')
      expect(bodyElement).toHaveClass('dm-sans-font')
      expect(bodyElement).toHaveClass('antialiased')
    })

    it('should render children content', () => {
      render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      expect(screen.getByText('Test Content')).toBeInTheDocument()
    })
  })

  describe('Providers', () => {
    it('should wrap children with NuqsAdapter', () => {
      render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      expect(screen.getByTestId('nuqs-adapter')).toBeInTheDocument()
    })

    it('should wrap children with TRPCReactProvider', () => {
      render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      expect(screen.getByTestId('trpc-provider')).toBeInTheDocument()
    })

    it('should render Toaster component', () => {
      render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      expect(screen.getByTestId('toaster')).toBeInTheDocument()
    })

    it('should have correct provider nesting order', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      
      const nuqsAdapter = container.querySelector('[data-testid="nuqs-adapter"]')
      const trpcProvider = container.querySelector('[data-testid="trpc-provider"]')
      
      expect(nuqsAdapter).toBeInTheDocument()
      expect(trpcProvider).toBeInTheDocument()
      
      // TRPCReactProvider should be inside NuqsAdapter
      expect(nuqsAdapter).toContainElement(trpcProvider!)
    })
  })

  describe('Metadata', () => {
    it('should export correct metadata', () => {
      expect(metadata).toBeDefined()
      expect(metadata.title).toBe('Create Next App')
      expect(metadata.description).toBe('Generated by create next app')
    })
  })

  describe('Google Analytics Removal', () => {
    it('should not include Google Analytics component', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      
      // Check that there's no GoogleAnalytics component
      const scriptTags = container.querySelectorAll('script')
      const hasGAScript = Array.from(scriptTags).some(
        (script) => script.textContent?.includes('G-6YG5QM4WK2') || 
                   script.src?.includes('googletagmanager')
      )
      
      expect(hasGAScript).toBe(false)
    })

    it('should not have any GA-related attributes or data', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      
      const htmlContent = container.innerHTML
      expect(htmlContent).not.toContain('G-6YG5QM4WK2')
      expect(htmlContent).not.toContain('GoogleAnalytics')
      expect(htmlContent).not.toContain('gtag')
    })
  })

  describe('Styling', () => {
    it('should include antialiased class for better font rendering', () => {
      const { container } = render(
        <RootLayout>
          <div>Test Content</div>
        </RootLayout>
      )
      const bodyElement = container.querySelector('body')
      expect(bodyElement).toHaveClass('antialiased')
    })
  })

  describe('Multiple Children', () => {
    it('should render multiple child elements', () => {
      render(
        <RootLayout>
          <div>First Child</div>
          <div>Second Child</div>
          <div>Third Child</div>
        </RootLayout>
      )
      
      expect(screen.getByText('First Child')).toBeInTheDocument()
      expect(screen.getByText('Second Child')).toBeInTheDocument()
      expect(screen.getByText('Third Child')).toBeInTheDocument()
    })
  })
})